name: Docker CI

on:
  push:
    branches:
      - api-branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Build Docker Compose
      run: docker compose build
